### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by Eljah** [masukomi/aspirin#7]
I'm trying to test just basic features:

```
import org.apache.log4j.ConsoleAppender;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.PatternLayout;
import org.masukomi.aspirin.Aspirin;
import org.masukomi.aspirin.core.AspirinInternal;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Message;
public class TestAspirin {
public static void main(String[] args) throws Exception
{

    Logger rootLogger = Logger.getRootLogger();
    rootLogger.setLevel(Level.TRACE);
    rootLogger.addAppender(new ConsoleAppender(
            new PatternLayout("%-6r [%p] %c - %m%n")));

    System.out.println("starting");
    MimeMessage message = AspirinInternal.createNewMimeMessage();

    message.setFrom(new InternetAddress("jUnit-aspirin-test@masukomi.org"));
    //message.addRecipient(Message.RecipientType.TO, new InternetAddress("aspirin-test@masukomi.org"));
    message.addRecipient(Message.RecipientType.TO, new InternetAddress("testname@mail.ru"));
    message.setSubject("Aspirin - test to show it doesn't shut down");
    message.setText("This is the text");
    Aspirin.add(message);
    System.out.println("queing mail");

}
```

}

So, almost all is like in the unit ttest description. When I'm running it, I'm getting

014-01-19 13:51:55,531 INFO  [Thread-1] Aspirin  Maintenance thread started.
0      [INFO] Aspirin  - Maintenance thread started.
queing mail
shutting down
2014-01-19 13:51:55,636 INFO  [Aspirin-DeliveryManager-9] Aspirin  DeliveryManager started.
105    [INFO] Aspirin  - DeliveryManager started.
2014-01-19 13:51:55,647 TRACE [Aspirin-DeliveryManager-9] Aspirin  DeliveryManager.run(): Pool state. A0/I0
116    [TRACE] Aspirin  - DeliveryManager.run(): Pool state. A0/I0
2014-01-19 13:51:55,647 DEBUG [Aspirin-DeliveryManager-9] Aspirin  DeliveryManager.run(): Start delivery. qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];
116    [DEBUG] Aspirin  - DeliveryManager.run(): Start delivery. qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];
2014-01-19 13:51:55,651 TRACE [Aspirin-DeliveryManager-9] Aspirin  GenericPoolableDeliveryThreadFactory.makeObject(): New DeliveryThread object created: DeliveryThread-1.
120    [TRACE] Aspirin  - GenericPoolableDeliveryThreadFactory.makeObject(): New DeliveryThread object created: DeliveryThread-1.
2014-01-19 13:51:55,655 TRACE [Aspirin-DeliveryManager-9] Aspirin  DeliveryManager.run(): Borrow DeliveryThread object. dt=DeliveryThread-1: state 'NEW/false'
124    [TRACE] Aspirin  - DeliveryManager.run(): Borrow DeliveryThread object. dt=DeliveryThread-1: state 'NEW/false'
2014-01-19 13:51:55,655 TRACE [Aspirin-DeliveryManager-9] Aspirin  DeliveryThread (DeliveryThread-1).setQuedItem(): Item was set. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
124    [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).setQuedItem(): Item was set. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
2014-01-19 13:51:55,656 TRACE [Aspirin-DeliveryManager-9] Aspirin  DeliveryManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
125    [TRACE] Aspirin  - DeliveryManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
2014-01-19 13:51:55,656 TRACE [DeliveryThread-1] Aspirin  DeliveryThread (DeliveryThread-1).run(): Call delivering... dCtx=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
125    [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).run(): Call delivering... dCtx=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
2014-01-19 13:51:55,671 INFO  [DeliveryThread-1] Aspirin  DeliveryThread (DeliveryThread-1).deliver(): Starting mail delivery. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
140    [INFO] Aspirin  - DeliveryThread (DeliveryThread-1).deliver(): Starting mail delivery. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
2014-01-19 13:51:56,155 TRACE [DeliveryThread-1] Aspirin  ResolveHost.handle(): 1 servers found for 'mail.ru'.
624    [TRACE] Aspirin  - ResolveHost.handle(): 1 servers found for 'mail.ru'.
2014-01-19 13:51:56,177 DEBUG [DeliveryThread-1] Aspirin  SendMessage.handle(): Attempting delivery of '1390125115.0' to recipient 'testname@mail.ru' on host 'smtp://mxs.mail.ru' 
646    [DEBUG] Aspirin  - SendMessage.handle(): Attempting delivery of '1390125115.0' to recipient 'testname@mail.ru' on host 'smtp://mxs.mail.ru' 
2014-01-19 13:51:56,306 INFO  [DeliveryThread-1] Aspirin  DeliveryThread (DeliveryThread-1).deliver(): Mail delivery failed: Нет маршрута до узла. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
775    [INFO] Aspirin  - DeliveryThread (DeliveryThread-1).deliver(): Mail delivery failed: Нет маршрута до узла. qi=DeliveryContext [qi=Mail: [id=1390125115.0; recipient=testname@mail.ru];]; 
2014-01-19 13:51:56,307 TRACE [DeliveryThread-1] Aspirin  DeliveryManager.release(): Release item '1390125115.0' with state: 'QUEUED' after 1 attempts.

Mail delivery failed reason is localized "No route to host".

That's is rather strange since when i do "traceroute mxs.mail.ru", I see the route. So what would be the reason why the Transport can't reach the host?

**Comment by Eljah** [comment]
Some little note. It looks like OS-specific. The previous log was done on the Linux machine, and this is the Windows output:

0      [INFO] Aspirin  - Maintenance thread started.
252    [INFO] Aspirin  - DeliveryManager started.
queing mail
60309  [TRACE] Aspirin  - DeliveryManager.run(): Pool state. A0/I0
60309  [DEBUG] Aspirin  - DeliveryManager.run(): Start delivery. qi=Mail: [id=1390126322.0; recipient=testname@mail.ru];
60311  [TRACE] Aspirin  - GenericPoolableDeliveryThreadFactory.makeObject(): New DeliveryThread object created: DeliveryThread-1.
60312  [TRACE] Aspirin  - DeliveryManager.run(): Borrow DeliveryThread object. dt=DeliveryThread-1: state 'NEW/false'
60312  [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).setQuedItem(): Item was set. qi=DeliveryContext [qi=Mail: [id=1390126322.0; recipient=testname@mail.ru];]; 
60313  [TRACE] Aspirin  - DeliveryManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
60314  [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).run(): Call delivering... dCtx=DeliveryContext [qi=Mail: [id=1390126322.0; recipient=testname@mail.ru];]; 
60323  [INFO] Aspirin  - DeliveryThread (DeliveryThread-1).deliver(): Starting mail delivery. qi=DeliveryContext [qi=Mail: [id=1390126322.0; recipient=testname@mail.ru];]; 
60629  [TRACE] Aspirin  - ResolveHost.handle(): 1 servers found for 'mail.ru'.
60688  [DEBUG] Aspirin  - SendMessage.handle(): Attempting delivery of '1390126322.0' to recipient 'testname@mail.ru' on host 'smtp://mxs.mail.ru' 
81770  [ERROR] Aspirin  - SendMessage.handle(): Connection failed.
javax.mail.MessagingException: Could not connect to SMTP host: mxs.mail.ru, port: 25;
  nested exception is:
    java.net.ConnectException: Connection timed out: connect
    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1545)
    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:453)
    at javax.mail.Service.connect(Service.java:291)
    at javax.mail.Service.connect(Service.java:172)
    at javax.mail.Service.connect(Service.java:121)
    at org.masukomi.aspirin.core.delivery.SendMessage.handle(SendMessage.java:60)
    at org.masukomi.aspirin.core.delivery.DeliveryThread.deliver(DeliveryThread.java:155)
    at org.masukomi.aspirin.core.delivery.DeliveryThread.run(DeliveryThread.java:90)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
    at java.net.Socket.connect(Socket.java:579)
    at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:265)
    at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:227)
    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1511)
    ... 7 more
81816  [INFO] Aspirin  - DeliveryThread (DeliveryThread-1).deliver(): Mail delivery failed: Connection timed out: connect. qi=DeliveryContext [qi=Mail: [id=1390126322.0; recipient=testname@mail.ru];]; 
81817  [TRACE] Aspirin  - DeliveryManager.release(): Release item '1390126322.0' with state: 'QUEUED' after 1 attempts.
81817  [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).run(): Try to give back DeliveryThread object into the pool.
81817  [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).run(): Wait for next sendable item.
120314 [TRACE] Aspirin  - DeliveryManager.run(): There is no sendable item in the queue. Fallback to waiting state for a minute.
141817 [TRACE] Aspirin  - DeliveryThread (DeliveryThread-1).run(): Wait for next sendable item
